runtime: php73

handlers:
- url: /css
  static_dir: public/css
- url: /js
  static_dir: public/js
- url: /img
  static_dir: public/img
- url: /favicon.ico
  static_dir: public/favicon


env_variables:
  APP_KEY: base64:MhwzyT9Tcr2BFwKP1i2T7bA+WL4VyPE9WBwV1wSQRsU=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie

  DB_CONNECTION: mysql
  DB_HOST: localhost
  DB_PORT: 3306
  DB_DATABASE: mypet
  DB_USERNAME: root
  DB_PASSWORD: rugbylove
  DB_SOCKET: /cloudsql/my-pet-318710:asia-northeast2:testsql
beta_settings:
  cloud_sql_instances: my-pet-318710:asia-northeast2:testsql


